# Generated by Django 5.2.7 on 2025-10-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='dep_decription',
            new_name='dep_description',
        ),
    ]
