# Generated by Django 5.2.7 on 2025-10-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='p_email',
            field=models.EmailField(max_length=254),
        ),
    ]
